// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostCore.Core.DbContext;

namespace PostCore.MainApp.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191126162610_Activities")]
    partial class Activities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostCore.Core.Activities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BranchId");

                    b.Property<long?>("CarId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Message");

                    b.Property<long>("PostId");

                    b.Property<int>("Type");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CarId");

                    b.HasIndex("PostId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("PostCore.Core.Branches.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("PostCore.Core.Cars.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("PostCore.Core.Mail.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressTo");

                    b.Property<long?>("BranchId");

                    b.Property<string>("BranchStockAddress");

                    b.Property<long?>("CarId");

                    b.Property<long?>("DestinationBranchId");

                    b.Property<string>("PersonFrom");

                    b.Property<string>("PersonTo");

                    b.Property<long?>("SourceBranchId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CarId");

                    b.HasIndex("DestinationBranchId");

                    b.HasIndex("SourceBranchId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("PostCore.Core.Activities.Activity", b =>
                {
                    b.HasOne("PostCore.Core.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PostCore.Core.Cars.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PostCore.Core.Mail.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PostCore.Core.Mail.Post", b =>
                {
                    b.HasOne("PostCore.Core.Branches.Branch", "Branch")
                        .WithMany("Mail")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PostCore.Core.Cars.Car", "Car")
                        .WithMany("Mail")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PostCore.Core.Branches.Branch", "DestinationBranch")
                        .WithMany("DestinationMail")
                        .HasForeignKey("DestinationBranchId");

                    b.HasOne("PostCore.Core.Branches.Branch", "SourceBranch")
                        .WithMany("SourceMail")
                        .HasForeignKey("SourceBranchId");
                });
#pragma warning restore 612, 618
        }
    }
}
